propertiesToScan: [Height, Width, X, Y, On]
objectsToScan:
    button: [Text]
    barcodeScanner: []
    form: [DataSource, Item]
    gallery: [Items]
    image: [Image]
    screen: []
    text: []
    rectangle: [ZIndex]
    icon: [Icon]
    container: []
    group: []
    label: []
    camera: []
    typedDataCard: []
    dropdown: []
    attachments: []


mermaidPrefix: "```mermaid"
mermaidSuffix: "```"